import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import toast from 'react-hot-toast';

const demos = [['Citizen', 'citizen@demo.in', 'demo1234', 'citizen'], ['Government Admin', 'admin@demo.in', 'admin1234', 'admin'], ['Institute / University', 'institution@demo.in', 'demo1234', 'institution'], ['Industry Partner', 'industry@demo.in', 'demo1234', 'industry']];

export default function Login() {
  const [email, setEmail] = useState('citizen@demo.in'); const [password, setPassword] = useState('demo1234'); const [role, setRole] = useState('citizen'); const [loading, setLoading] = useState(false); const { login } = useAuth(); const navigate = useNavigate();
  useEffect(() => { const demo = demos.find(item => item[3] === role); if (demo) { setEmail(demo[1]); setPassword(demo[2]); } }, [role]);
  const fill = demo => { setEmail(demo[1]); setPassword(demo[2]); setRole(demo[3]); };
  const submit = async event => { event.preventDefault(); setLoading(true); try { await login({ email, password, role }); toast.success('Signed in successfully.'); const destination = role === 'citizen' ? '/dashboard' : role === 'institution' ? '/institution/directory' : role === 'industry' ? '/industry/dashboard' : '/admin/dashboard'; navigate(destination, { replace: true }); } catch (error) { toast.error(error.response?.data?.error || 'Login failed. Please check your credentials.'); } finally { setLoading(false); } };
  return <div className="gov-login"><div className="gov-strip"><span>Government of India</span><span>Digital civic services portal</span></div><main className="login-frame"><section className="login-intro"><div className="gov-emblem">S</div><p className="eyebrow">SAMVEDANA SETU</p><h1>One bridge for every community problem.</h1><p className="intro-copy">Report local issues, connect them with capable institutions and industry partners, and follow the solution from verification to impact.</p><div className="service-points"><span>Secure role-based access</span><span>AI-assisted classification</span><span>Transparent public progress</span></div></section><section className="login-panel"><div className="login-panel-head"><div><p className="eyebrow">Citizen services</p><h2>Sign in to Samvedana Setu</h2></div><span className="proto-badge">Prototype Demo</span></div><form onSubmit={submit}><div className="field"><label>Sign in as</label><select value={role} onChange={e => setRole(e.target.value)}><option value="citizen">Citizen / User</option><option value="institution">Institute / University</option><option value="industry">Industry Partner</option><option value="admin">Government / Admin</option></select></div><div className="field"><label>Email address</label><input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="name@example.com" required /></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter your password" required /></div><button type="submit" disabled={loading} className="btn btn-primary btn-block login-submit">{loading ? 'Signing in...' : 'Sign in securely'}</button></form><div className="demo-section"><p className="demo-title">Demo access</p><p className="text-muted">Select a portal to autofill its sample account.</p><div className="demo-grid">{demos.map(demo => <button type="button" className={`demo-account ${role === demo[3] ? 'selected' : ''}`} key={demo[3]} onClick={() => fill(demo)}><b>{demo[0]}</b><small>{demo[1]}</small></button>)}</div></div><p className="login-footer">New citizen? <Link to="/register">Create an account</Link></p></section></main><footer className="gov-footer">Accessible public service platform <span>·</span> Privacy <span>·</span> Helpdesk</footer></div>;
}
