import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { getChallenge } from '../../api/client';

const baseStages = ['Submitted', 'AI Analyzed', 'Government Approval', 'Matched', 'Institute Assigned', 'Team Formation', 'Solution Proposal', 'Prototype/Pilot', 'Closed'];
const collaborationStages = ['Submitted', 'AI Analyzed', 'Government Approval', 'Matched', 'Institute Assigned', 'Team Formation', 'Collaboration Requested', 'Collaboration Accepted', 'Solution Proposal', 'Prototype/Pilot', 'Closed'];
const aliases = { Accepted: 'Institute Assigned', 'Admin Approval': 'Government Approval', 'In Progress': 'Prototype/Pilot', Implemented: 'Closed', Resolved: 'Closed' };

export default function ChallengeDetail() {
  const { id } = useParams(); const [item, setItem] = useState(null); useEffect(() => { getChallenge(id).then(response => setItem(response.data?.data)).catch(() => {}); }, [id]);
  if (!item) return <div className="card card-pad">Loading problem tracking...</div>;
  const project = item.projects?.[0]; const submission = project?.testingRecords?.find(record => ['prototype', 'solution'].includes(record.testType)); const collaborationAccepted = project?.partnerInterests?.some(interest => interest.status === 'accepted'); const collaborationRequested = project?.partnerInterests?.some(interest => ['interest_submitted', 'accepted'].includes(interest.status)); const stages = collaborationAccepted || collaborationRequested ? collaborationStages : baseStages; const displayedStatus = project?.status || item.status; const current = stages.indexOf(aliases[displayedStatus] || displayedStatus);
  return <div><div className="page-head"><h2>Track {item.displayId}</h2><p>{item.title}</p></div><div className="card card-pad"><h3>Public progress timeline</h3>{item.status === 'Rejected' ? <><p className="text-muted">This report was rejected. Reason: {item.rejectionReason || 'Not verified.'}</p><Link className="btn btn-primary btn-sm" to="/report">Submit a corrected problem</Link></> : <><p className="text-muted">{collaborationAccepted ? 'Industry collaboration is active for this solution.' : collaborationRequested ? 'Industry collaboration is awaiting a response.' : 'Direct institute solution path. Industry collaboration is not required.'}</p><div className="flow-steps" style={{ marginTop: 18 }}>{stages.map((stage, index) => <div className={`flow-step ${index <= current ? 'active' : ''}`} key={stage}><span className="flow-check">{index <= current ? '✓' : '○'}</span>{stage}</div>)}</div>{submission && <div className="card card-pad" style={{ marginTop: 18 }}><h3>Submitted solution</h3><p className="text-muted">Submitted by: {submission.submittedByRole === 'industry_partner' ? 'Industry partner' : 'Institute'}</p><p>{submission.resultSummary || 'Solution submitted for Government review.'}</p>{submission.evidenceUrl && <p><a href={submission.evidenceUrl} target="_blank" rel="noreferrer">View submitted evidence</a></p>}</div>}</>}</div></div>;
}
