import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { getChallenge } from '../../api/client';

const baseStages = ['Submitted', 'AI Analyzed', 'Government Approval', 'Matched', 'Institute Assigned', 'Team Formation', 'Solution Proposal', 'Prototype/Pilot', 'Closed'];
const collaborationStages = ['Submitted', 'AI Analyzed', 'Government Approval', 'Matched', 'Institute Assigned', 'Team Formation', 'Collaboration Requested', 'Collaboration Accepted', 'Solution Proposal', 'Prototype/Pilot', 'Closed'];
const aliases = { Accepted: 'Institute Assigned', 'Admin Approval': 'Government Approval', 'Industry Collaboration': 'Collaboration Requested', 'In Progress': 'Prototype/Pilot', Implemented: 'Closed', Resolved: 'Closed' };

function SubmissionList({ records }) {
  if (!records?.length) return null;
  return <div className="card card-pad" style={{ marginTop: 18 }}><h3>Submitted prototype and solution evidence</h3>{records.map(record => <div key={record.id} style={{ borderTop: '1px solid var(--border)', padding: '14px 0' }}><p><b>{record.testType === 'solution' ? 'Solution' : 'Prototype'}</b> · Submitted by: {record.submittedByRole === 'industry_partner' ? 'Industry partner' : record.submittedByRole === 'university_admin' || record.submittedByRole === 'faculty_mentor' ? 'Institute' : record.submittedByRole || 'Project team'}</p>{record.resultSummary && <p>{record.resultSummary}</p>}{record.evidenceUrl && <p><a href={record.evidenceUrl} target="_blank" rel="noreferrer">Open submitted evidence</a></p>}</div>)}</div>;
}

export default function ChallengeDetail() {
  const { id } = useParams(); const [item, setItem] = useState(null); useEffect(() => { getChallenge(id).then(response => setItem(response.data?.data)).catch(() => {}); }, [id]);
  if (!item) return <div className="card card-pad">Loading problem tracking...</div>;
  const project = item.projects?.[0]; const collaborationAccepted = project?.partnerInterests?.some(interest => interest.status === 'accepted'); const collaborationRequested = project?.partnerInterests?.some(interest => ['interest_submitted', 'accepted'].includes(interest.status)); const stages = collaborationAccepted || collaborationRequested ? collaborationStages : baseStages; const displayedStatus = project?.status || item.status; const current = stages.indexOf(aliases[displayedStatus] || displayedStatus);
  return <div><div className="page-head"><h2>Track {item.displayId}</h2><p>{item.title}</p></div><div className="card card-pad"><h3>Who is solving this problem?</h3>{project?.university && <p><b>Institute:</b> {project.university.name}</p>}{project?.partnerInterests?.length ? project.partnerInterests.map((interest, index) => <p key={`${interest.industryOrg?.name || 'partner'}-${index}`}><b>Industry partner:</b> {interest.industryOrg?.name || 'Partner assigned'} · Status: {interest.status}</p>) : !project?.university && <p className="text-muted">No institute or industry partner has been assigned yet.</p>}</div><div className="card card-pad" style={{ marginTop: 20 }}><h3>Public progress timeline</h3>{item.status === 'Rejected' ? <><p className="text-muted">This report was rejected. Reason: {item.rejectionReason || 'Not verified.'}</p><Link className="btn btn-primary btn-sm" to="/report">Submit a corrected problem</Link></> : <><p className="text-muted">{collaborationAccepted ? 'Industry collaboration is active for this solution.' : collaborationRequested ? 'Industry collaboration is awaiting a response.' : 'Direct institute solution path. Industry collaboration is not required.'}</p><div className="flow-steps" style={{ marginTop: 18 }}>{stages.map((stage, index) => <div className={`flow-step ${index <= current ? 'active' : ''}`} key={stage}><span className="flow-check">{index <= current ? '✓' : '○'}</span>{stage}</div>)}</div><SubmissionList records={project?.testingRecords} /></>}</div></div>;
}
