import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import StatCard from '../../components/StatCard';
import { useAuth } from '../../contexts/AuthContext';
import { getChallenges } from '../../api/client';

export default function Dashboard() {
  const { user } = useAuth();
  const [items, setItems] = useState([]);
  useEffect(() => { getChallenges().then(r => setItems(r.data?.data || [])).catch(() => {}); }, []);
  const stats = useMemo(() => ({ total: items.length, unresolved: items.filter(x => !['Resolved', 'Closed'].includes(x.status)).length, resolved: items.filter(x => ['Resolved', 'Closed'].includes(x.status)).length, high: items.filter(x => ['High', 'Critical'].includes(x.severity)).length }), [items]);
  const insight = useMemo(() => { const counts = items.reduce((map, item) => { map[item.category] = (map[item.category] || 0) + 1; return map; }, {}); const hotspot = Object.entries(counts).sort((a, b) => b[1] - a[1])[0]; const urgent = items.filter(item => ['High', 'Critical'].includes(item.severity)).length; return { hotspot: hotspot ? `${hotspot[0]} leads with ${hotspot[1]} report${hotspot[1] === 1 ? '' : 's'}.` : 'No category trend detected yet.', urgent: urgent ? `${urgent} high-priority report${urgent === 1 ? '' : 's'} may need faster verification.` : 'No high-priority reports are currently visible.', recommendation: stats.unresolved ? 'Prioritise verified unresolved reports and monitor progress on the live map.' : 'Keep reporting local issues so AI can identify useful community patterns.' }; }, [items, stats.unresolved]);
  return <div><div className="page-head"><h2>Community dashboard</h2><p>Real-time community reports, resolution progress, and local insights for {user?.district || 'your area'}.</p></div><div className="stat-grid"><StatCard title="Total Reported" value={stats.total} /><StatCard title="Unresolved" value={stats.unresolved} variant="review" /><StatCard title="Resolved" value={stats.resolved} variant="accepted" /><StatCard title="High Priority" value={stats.high} variant="matched" /></div><div className="quick-actions"><Link to="/report" className="qa-card"><div className="qa-ico">+</div><div><b>Report an issue</b><span>Describe or photograph a problem</span></div></Link><Link to="/live-map" className="qa-card"><div className="qa-ico">Map</div><div><b>Live incident map</b><span>Explore local reports</span></div></Link><Link to="/challenges" className="qa-card"><div className="qa-ico">Track</div><div><b>Track my reports</b><span>Follow solution progress</span></div></Link></div><section className="insight-panel card card-pad"><h3>AI community insights</h3><p className="text-muted">Live recommendations generated from your current report data.</p><div className="insight-grid"><div><b>Category signal</b><span>{insight.hotspot}</span><Link to="/live-map">Explore live map</Link></div><div><b>Priority alert</b><span>{insight.urgent}</span><Link to="/challenges">View reports</Link></div><div><b>Recommended action</b><span>{insight.recommendation}</span><Link to="/report">Report an issue</Link></div></div></section></div>;
}
