import React, { useEffect, useMemo, useState } from 'react';
import { MapContainer, Marker, Popup, TileLayer, useMap } from 'react-leaflet';
import L from 'leaflet';
import { getLiveMapChallenges, getInstitutions, getProjects } from '../../api/client';
import 'leaflet/dist/leaflet.css';

const statusColors = { Submitted: '#94a3b8', 'Under Review': '#f59e0b', Verified: '#12cde5', Matched: '#6475ff', 'Organizations Notified': '#6475ff', Assigned: '#f97316', 'In Progress': '#22c55e', Resolved: '#10b981', Closed: '#10b981' };
const pin = (symbol, color) => L.divIcon({ className: 'setu-map-pin', html: `<span style="background:${color}">${symbol}</span>`, iconSize: [34, 34], iconAnchor: [17, 17] });
const locationText = item => [item.village, item.block, item.district].filter(Boolean).join(', ') || 'Location not provided';
const coordinatesText = item => item.latitude != null && item.longitude != null ? `${Number(item.latitude).toFixed(6)}, ${Number(item.longitude).toFixed(6)}` : 'Coordinates not provided';
function Locate({ position }) { const map = useMap(); useEffect(() => { if (position) map.setView(position, 13); }, [position, map]); return null; }

export default function LiveMap() {
  const [items, setItems] = useState([]); const [projects, setProjects] = useState([]); const [institutions, setInstitutions] = useState([]); const [filter, setFilter] = useState('All'); const [query, setQuery] = useState(''); const [position, setPosition] = useState(null); const [layers, setLayers] = useState({ problems: true, projects: true, institutions: false, industry: false });
  useEffect(() => { getLiveMapChallenges().then(r => setItems(r.data?.data || [])).catch(() => {}); getProjects().then(r => setProjects(r.data?.data || [])).catch(() => {}); getInstitutions().then(r => setInstitutions(r.data?.data || [])).catch(() => {}); }, []);
  const visible = useMemo(() => items.filter(x => (filter === 'All' || x.status === filter) && `${x.title} ${x.district || ''}`.toLowerCase().includes(query.toLowerCase())), [items, filter, query]);
  const locate = () => navigator.geolocation?.getCurrentPosition(({ coords }) => setPosition([coords.latitude, coords.longitude]));
  const toggle = key => setLayers(current => ({ ...current, [key]: !current[key] }));
  return <div><div className="page-head"><h2>Live incident map</h2><p>Filter and locate hyperlocal problems, projects, and civic partners. Problems reported by all citizens are shown here.</p></div><div className="map-toolbar"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search location or incident..." /><button className="btn btn-secondary" onClick={locate}>Use my location</button><select value={filter} onChange={e => setFilter(e.target.value)}><option>All</option><option>Submitted</option><option>Under Review</option><option>Verified</option><option>Matched</option><option>In Progress</option><option>Resolved</option></select></div><div className="map-layer-bar">{[['problems', '● Problems'], ['projects', '◆ Projects'], ['institutions', '■ Institutions'], ['industry', '★ Industry']].map(([key, label]) => <button key={key} className={layers[key] ? 'layer-active' : ''} onClick={() => toggle(key)}>{label}</button>)}</div><div className="card" style={{ overflow: 'hidden' }}><MapContainer center={position || [20.5937, 78.9629]} zoom={position ? 13 : 5} style={{ height: 'calc(100vh - 330px)', minHeight: 430 }}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Locate position={position} />{layers.problems && visible.filter(x => x.latitude != null && x.longitude != null).map(x => <Marker key={`c-${x.id}`} position={[x.latitude, x.longitude]} icon={pin('!', statusColors[x.status] || '#6475ff')}><Popup><b>{x.displayId} · {x.title}</b><br />{x.status} · {x.severity || 'Unclassified'}<br /><b>Reported by:</b> {x.reportedBy}<br /><b>Location:</b> {locationText(x)}<br /><b>Coordinates:</b> {coordinatesText(x)}</Popup></Marker>)}{layers.projects && projects.filter(x => x.challenge?.latitude != null && x.challenge?.longitude != null).map(x => <Marker key={`p-${x.id}`} position={[x.challenge.latitude, x.challenge.longitude]} icon={pin('◆', '#a855f7')}><Popup><b>{x.displayId} · {x.title}</b><br />Project: {x.status}<br /><b>Location:</b> {locationText(x.challenge)}<br /><b>Coordinates:</b> {coordinatesText(x.challenge)}</Popup></Marker>)}{layers.institutions && institutions.filter(x => x.latitude && x.longitude).map(x => <Marker key={`i-${x.id}`} position={[x.latitude, x.longitude]} icon={pin('■', '#06b6d4')}><Popup><b>{x.name}</b><br />Institute partner<br /><b>Coordinates:</b> {coordinatesText(x)}</Popup></Marker>)}</MapContainer></div><p className="text-muted" style={{ marginTop: 10 }}>{visible.length} incidents shown · marker colors represent lifecycle status.</p></div>;
}
