import React, { useEffect, useState } from 'react';
import { getMyInterests } from '../../api/client';

export default function IndustryDashboard() {
  const [items, setItems] = useState([]);
  useEffect(() => { getMyInterests().then(response => setItems(response.data?.data || [])).catch(() => {}); }, []);
  const pending = items.filter(item => ['interest_submitted', 'pending'].includes(item.status)).length;
  const accepted = items.filter(item => item.status === 'accepted').length;
  const declined = items.filter(item => item.status === 'declined').length;
  const active = items.filter(item => item.status === 'accepted' && item.projectId).length;
  const total = Math.max(items.length, 1);
  const chart = [['Pending', pending, '#f5b942'], ['Accepted', accepted, '#0b8f68'], ['Active', active, '#0b8fa3'], ['Declined', declined, '#ef6b73']];
  return <div><div className="page-head"><h2>Industry partner dashboard</h2><p>Insights from your collaboration requests, accepted projects, and community support.</p></div><div className="stat-grid"><div className="card card-pad"><span className="text-muted">Total requests</span><h2>{items.length}</h2></div><div className="card card-pad"><span className="text-muted">Accepted collaborations</span><h2>{accepted}</h2></div><div className="card card-pad"><span className="text-muted">Active projects</span><h2>{active}</h2></div><div className="card card-pad"><span className="text-muted">Declined requests</span><h2>{declined}</h2></div></div><div className="card card-pad" style={{ marginTop: 20 }}><h3>Collaboration insights</h3><p className="text-muted">Current status of your industry participation.</p><div style={{ display: 'grid', gridTemplateColumns: 'minmax(180px, 240px) 1fr', gap: 30, alignItems: 'center', marginTop: 20 }}><div style={{ width: 190, height: 190, borderRadius: '50%', background: `conic-gradient(#f5b942 0 ${pending / total * 100}%, #0b8f68 ${pending / total * 100}% ${(pending + accepted) / total * 100}%, #0b8fa3 ${(pending + accepted) / total * 100}% ${(pending + accepted + active) / total * 100}%, #ef6b73 ${(pending + accepted + active) / total * 100}% 100%)`, display: 'grid', placeItems: 'center' }}><div style={{ width: 105, height: 105, borderRadius: '50%', background: 'var(--surface, white)', display: 'grid', placeItems: 'center', textAlign: 'center' }}><b>{items.length}</b><small>Total</small></div></div><div>{chart.map(([label, value, color]) => <div key={label} style={{ display: 'grid', gridTemplateColumns: '110px 1fr 35px', gap: 10, alignItems: 'center', margin: '14px 0' }}><span><i style={{ display: 'inline-block', width: 10, height: 10, borderRadius: '50%', background: color, marginRight: 8 }} />{label}</span><div style={{ height: 10, background: 'var(--border)', borderRadius: 8 }}><div style={{ width: `${value / total * 100}%`, height: '100%', background: color, borderRadius: 8 }} /></div><b>{value}</b></div>)}</div></div></div><div className="card card-pad" style={{ marginTop: 20 }}><h3>Partner insight</h3><p className="text-muted">{accepted ? `Your team has accepted ${accepted} collaboration${accepted === 1 ? '' : 's'}${active ? ` and is actively supporting ${active} project${active === 1 ? '' : 's'}` : ''}.` : pending ? `You have ${pending} collaboration request${pending === 1 ? '' : 's'} waiting for a response.` : 'No collaboration activity yet. Government-notified problems will appear in Collaboration Requests.'}</p></div></div>;
}
