import React, { useEffect, useState } from 'react';
import { getIndustryPartners, getProjects, requestIndustrySupport } from '../../api/client';
import toast from 'react-hot-toast';

const supportOptions = ['expertise', 'funding', 'equipment', 'prototyping', 'testing', 'field deployment'];
const activeRequestStatuses = ['interest_submitted', 'accepted'];
const projectStatuses = ['Accepted', 'Team Formation', 'Admin Approval', 'Industry Collaboration', 'Solution Proposal', 'In Progress'];

export default function IndustryCollaboration() {
  const [projects, setProjects] = useState([]); const [selectedProject, setSelectedProject] = useState(''); const [partners, setPartners] = useState([]); const [support, setSupport] = useState(['expertise']); const [sent, setSent] = useState({}); const [matching, setMatching] = useState(false);
  useEffect(() => { getProjects().then(response => { const items = (response.data?.data || []).filter(project => projectStatuses.includes(project.status) && !project.partnerInterests?.some(item => activeRequestStatuses.includes(item.status))); setProjects(items); if (items[0]) setSelectedProject(String(items[0].id)); }).catch(error => toast.error(error.response?.data?.error || 'Could not load institute projects.')); }, []);
  const findMatches = () => { const project = projects.find(item => String(item.id) === selectedProject); if (!project) return; setMatching(true); getIndustryPartners(project.challengeId).then(response => setPartners(response.data?.data || [])).catch(() => setPartners([])).finally(() => setMatching(false)); };
  const request = partner => { const project = projects.find(item => String(item.id) === selectedProject); if (!project || !partner?.partner?.id) return; requestIndustrySupport(project.challengeId, { projectId: project.id, industryOrgId: partner.partner.id, supportTypes: support, message: `Please collaborate on ${project.title}. Requested support: ${support.join(', ')}.` }).then(response => { setSent(current => ({ ...current, [partner.partner.id]: true })); setProjects(current => current.filter(item => item.id !== project.id)); setSelectedProject(''); setPartners([]); toast.success(response.data?.notified ? `Request sent to ${partner.partner.name}.` : 'Request saved, but no active industry account is linked yet.'); }).catch(error => toast.error(error.response?.data?.error || 'Could not send the collaboration request.')); };
  return <div><div className="page-head"><h2>Industry collaboration</h2><p>After forming an institute team, choose the strongest industry match and request the resources you need.</p></div><div className="card card-pad"><label>Project needing support<select value={selectedProject} onChange={event => { setSelectedProject(event.target.value); setSent({}); setPartners([]); }}><option value="">Select a project</option>{projects.map(project => <option key={project.id} value={project.id}>{project.displayId} · {project.title}</option>)}</select></label><p className="text-muted" style={{ marginTop: 14 }}>Match requirements: select one or more collaboration needs before notifying an industry partner.</p><div className="choice-grid">{supportOptions.map(option => <label className="checkbox-card" key={option}><input type="checkbox" checked={support.includes(option)} onChange={event => setSupport(current => event.target.checked ? [...current, option] : current.filter(item => item !== option))} /><span><b>{option[0].toUpperCase() + option.slice(1)}</b><small>Industry contribution</small></span></label>)}</div><button className="btn btn-primary" style={{ marginTop: 16 }} onClick={findMatches} disabled={!selectedProject || matching}>{matching ? 'Matching industry partners...' : 'Match industry partners'}</button></div><div className="card" style={{ marginTop: 20 }}><div className="card-head"><div><h3>AI-ranked industry partners</h3><p className="text-muted">The highest score is the closest match for this project’s category, expertise, location, and resources.</p></div></div>{partners.length ? partners.map(item => { const alreadyRequested = sent[item.partner.id] || activeRequestStatuses.includes(item.requestStatus); return <div className="card-pad" key={item.partner.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, borderBottom: '1px solid var(--border)' }}><span><b>{item.partner.name}</b><small style={{ display: 'block', color: 'var(--text-muted)' }}>{item.partner.district || 'Location not listed'} · {item.partner.type}</small><small style={{ display: 'block', color: 'var(--text-muted)' }}>{item.matchedFocusAreas?.join(' · ') || 'General civic support'}</small></span><strong style={{ color: 'var(--setu-cyan)', fontSize: 20 }}>{item.matchScore}%</strong><button className="btn btn-primary btn-sm" onClick={() => request(item)} disabled={alreadyRequested}>{alreadyRequested ? 'Request sent' : 'Request collaboration'}</button></div>; }) : <div className="card-pad">Create or select a project first to see matched industry partners.</div>}</div></div>;
}
