import React, { useEffect, useState } from 'react';
import { getInstitutions, getProjects } from '../../api/client';

export default function InstitutionDashboard() {
  const [institutions, setInstitutions] = useState([]);
  const [projects, setProjects] = useState([]);
  useEffect(() => { Promise.all([getInstitutions(), getProjects()]).then(([directory, projectList]) => { setInstitutions(directory.data?.data || []); setProjects(projectList.data?.data || []); }).catch(() => {}); }, []);
  const max = Math.max(...institutions.map(item => Math.max(item.solvedProjects || 0, item.acceptedProblems || 0, item.rejectedProblems || 0)), 1);
  const totalAccepted = institutions.reduce((sum, item) => sum + (item.acceptedProblems || 0), 0);
  const totalRejected = institutions.reduce((sum, item) => sum + (item.rejectedProblems || 0), 0);
  return <div><div className="page-head"><h2>Institute performance dashboard</h2><p>Compare community solutions, acceptance, and rejection activity across the institute network.</p></div><div className="stat-grid"><div className="card card-pad"><span className="text-muted">Institutes</span><h2>{institutions.length}</h2></div><div className="card card-pad"><span className="text-muted">Projects solved</span><h2>{institutions.reduce((sum, item) => sum + (item.solvedProjects || 0), 0)}</h2></div><div className="card card-pad"><span className="text-muted">Problems accepted</span><h2>{totalAccepted}</h2></div><div className="card card-pad"><span className="text-muted">Problems rejected</span><h2>{totalRejected}</h2></div></div><div className="card card-pad" style={{ marginTop: 20 }}><h3>Institute performance</h3><p className="text-muted">Column chart: solved projects, accepted problems, and rejected problems.</p><div className="institute-chart">{institutions.map(item => <div className="institute-chart-column" key={item.id}><div className="chart-bars"><span className="chart-bar solved" style={{ height: `${Math.max(8, (item.solvedProjects || 0) / max * 150)}px` }} title={`${item.solvedProjects || 0} solved`} /><span className="chart-bar accepted" style={{ height: `${Math.max(8, (item.acceptedProblems || 0) / max * 150)}px` }} title={`${item.acceptedProblems || 0} accepted`} /><span className="chart-bar rejected" style={{ height: `${Math.max(8, (item.rejectedProblems || 0) / max * 150)}px` }} title={`${item.rejectedProblems || 0} rejected`} /></div><b>{item.name.replace('Institution ', '')}</b><small>{item.solvedProjects || 0} solved</small></div>)}</div><div className="chart-legend"><span><i className="solved" /> Solved</span><span><i className="accepted" /> Accepted</span><span><i className="rejected" /> Rejected</span></div></div><div className="card card-pad" style={{ marginTop: 20 }}><h3>Top institute</h3><p className="text-muted">{[...institutions].sort((a, b) => (b.solvedProjects || 0) - (a.solvedProjects || 0))[0]?.name || 'No institute data yet'} currently has the highest number of solved projects.</p><p className="text-muted">Active projects across your institute account: {projects.filter(item => item.status !== 'Closed').length}</p></div></div>;
}
