import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getProjects, updateProjectStatus } from '../../api/client';

export default function MyProjects() {
  const [items, setItems] = useState([]);
  useEffect(() => { getProjects().then(response => setItems(response.data?.data || [])).catch(() => setItems([])); }, []);
  const grouped = items.reduce((groups, project) => { const key = project.university?.id || 'unassigned'; (groups[key] ||= { name: project.university?.name || 'Institute', projects: [] }).projects.push(project); return groups; }, {});
  const submitted = project => ['Closed', 'Submitted'].includes(project.status);
  const solve = project => updateProjectStatus(project.id, { status: 'Closed' }).then(() => setItems(current => current.map(item => item.id === project.id ? { ...item, status: 'Closed' } : item)));
  return <div><div className="page-head"><h2>Accepted projects</h2><p>View accepted projects institute-wise and manage teams, collaboration, prototypes, and solutions.</p></div><div className="stat-grid"><div className="card card-pad"><span className="text-muted">Accepted projects</span><h2>{items.length}</h2></div><div className="card card-pad"><span className="text-muted">Institutes</span><h2>{Object.keys(grouped).length}</h2></div><div className="card card-pad"><span className="text-muted">In progress</span><h2>{items.filter(item => !submitted(item)).length}</h2></div><div className="card card-pad"><span className="text-muted">Projects submitted</span><h2>{items.filter(submitted).length}</h2></div></div>{Object.values(grouped).length ? Object.values(grouped).map(group => <div className="card" style={{ marginTop: 20 }} key={group.name}><div className="card-head"><div><h3>{group.name}</h3><p className="text-muted">{group.projects.length} accepted project{group.projects.length === 1 ? '' : 's'} assigned to this institute.</p></div></div>{group.projects.map(project => <div className="card-pad" key={project.id} style={{ borderTop: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, flexWrap: 'wrap' }}><div><h3>{project.displayId} · {project.title}</h3><p className="text-muted">{project.challenge?.category || 'Community problem'} · Stage: <b>{submitted(project) ? 'Submitted' : project.status}</b></p></div><div>{submitted(project) ? <span className="btn btn-secondary btn-sm">Submitted</span> : <><Link className="btn btn-primary btn-sm" to={`/institution/projects/${project.id}`}>Manage team</Link><button className="btn btn-secondary btn-sm" style={{ marginLeft: 8 }} onClick={() => solve(project)}>Mark project solved</button></>}</div></div>)}</div>) : <div className="card card-pad" style={{ marginTop: 20 }}>No accepted projects yet. Accept a Government-notified problem from All Institutes to create one.</div>}</div>;
}
