import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Bar, Doughnut } from 'react-chartjs-2';
import { Chart as ChartJS, ArcElement, BarElement, CategoryScale, LinearScale, Legend, Tooltip } from 'chart.js';
import { getAnalyticsOverview, getChallenges } from '../../api/client';
ChartJS.register(ArcElement, BarElement, CategoryScale, LinearScale, Legend, Tooltip);

export default function AdminDashboard() {
  const [analytics, setAnalytics] = useState({}); const [reports, setReports] = useState([]);
  useEffect(() => { getAnalyticsOverview().then(r => setAnalytics(r.data?.data || {})).catch(() => {}); getChallenges({ status: 'Submitted' }).then(r => setReports(r.data?.data || [])).catch(() => {}); }, []);
  const statusData = { labels: ['Pending', 'Active', 'Resolved'], datasets: [{ data: [analytics.pending || 0, analytics.active || 0, analytics.resolved || 0], backgroundColor: ['#f59e0b', '#12cde5', '#10b981'], borderWidth: 0 }] };
  const categoryCounts = reports.reduce((all, report) => { all[report.category] = (all[report.category] || 0) + 1; return all; }, {});
  const categoryData = { labels: Object.keys(categoryCounts).length ? Object.keys(categoryCounts) : ['No pending reports'], datasets: [{ data: Object.values(categoryCounts).length ? Object.values(categoryCounts) : [0], backgroundColor: '#12cde5', borderRadius: 6 }] };
  return <div><div className="page-head"><h2>Government coordination dashboard</h2><p>Verify reports, coordinate matching, and monitor community impact.</p></div><div className="stat-grid">{[['Total reports', analytics.total], ['Pending verification', analytics.pending], ['Active projects', analytics.active], ['Resolved', analytics.resolved]].map(([label, value]) => <div className="card card-pad" key={label}><span className="text-muted">{label}</span><h2>{value ?? '...'}</h2></div>)}</div><div className="admin-chart-grid"><div className="card card-pad"><h3>Incident status</h3><div className="chart-box"><Doughnut data={statusData} options={{ plugins: { legend: { labels: { color: '#a6b3c9' } } }, maintainAspectRatio: false }} /></div></div><div className="card card-pad"><h3>Pending report categories</h3><div className="chart-box"><Bar data={categoryData} options={{ plugins: { legend: { display: false } }, scales: { x: { ticks: { color: '#a6b3c9' }, grid: { display: false } }, y: { ticks: { color: '#a6b3c9', stepSize: 1 }, grid: { color: '#26344d' } } }, maintainAspectRatio: false }} /></div></div></div><div className="card" style={{ marginTop: 20 }}><div className="card-head"><h3>Reports awaiting verification</h3><Link className="btn btn-secondary btn-sm" to="/admin/verification">Open queue</Link></div>{reports.length ? reports.slice(0, 5).map(report => <div key={report.id} className="admin-report-row"><b>{report.displayId}</b><span>{report.title}</span><span className="text-muted">{report.district || 'Location pending'}</span><span>{report.severity || 'Unclassified'}</span><Link className="btn btn-primary btn-sm" to="/admin/verification">Review</Link></div>) : <div className="card-pad">No pending reports.</div>}</div><div className="card card-pad" style={{ marginTop: 20 }}><h3>Workflow controls</h3><p className="text-muted">Organization approvals, verification, matching, and project outcomes are managed from this portal.</p><Link className="btn btn-primary" to="/admin/organizations">Organization approvals</Link><Link className="btn btn-secondary" style={{ marginLeft: 8 }} to="/admin/matching">Open matching</Link></div></div>;
}
