import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { getChallenges, notifyOrganization, runMatching } from '../../api/client';

export default function MatchingPage() {
  const [problems, setProblems] = useState([]); const [selected, setSelected] = useState(''); const [result, setResult] = useState(null); const [loading, setLoading] = useState(false); const [sent, setSent] = useState({});
  useEffect(() => { getChallenges().then(response => { const items = (response.data?.data || []).filter(item => ['Verified', 'Matched', 'Organizations Notified'].includes(item.status)); setProblems(items); if (items[0]) setSelected(String(items[0].id)); }).catch(() => toast.error('Could not load verified problems.')); }, []);
  const match = () => { if (!selected) return; setLoading(true); runMatching(selected).then(response => { setResult(response.data?.data || {}); toast.success('Matches calculated. Only the highest-match institute can be notified.'); }).catch(error => toast.error(error.response?.data?.error || 'Matching failed.')).finally(() => setLoading(false)); };
  const notify = (type, organizationId, matchScore) => notifyOrganization(selected, { organizationType: type, organizationId, matchScore }).then(() => { setSent(current => ({ ...current, [`${type}-${organizationId}`]: true })); toast.success('Problem added to the selected organization account.'); }).catch(error => toast.error(error.response?.data?.error || 'Could not send notification.'));
  const orgRow = (type, item, isTop) => { const org = type === 'institution' ? item.institution : item.partner; const key = `${type}-${org.id}`; return <div className="match-result-row" key={org.id}><span><b>{org.name}{isTop ? ' - Highest match' : ''}</b><small>{org.district || 'Location pending'} - {org.type}</small></span><strong>{item.matchScore}%</strong>{!isTop ? <span className="text-muted">Not selected</span> : <button className="btn btn-primary btn-sm" onClick={() => notify(type, org.id, item.matchScore)} disabled={sent[key]}>{sent[key] ? 'Added to account' : type === 'institution' ? 'Notify top match' : 'Notify top partner'}</button>}</div>; };
  return <div><div className="page-head"><h2>AI matching engine</h2><p>Select a verified problem and notify the highest-match institute. The problem will appear only in that institute account.</p></div><div className="card card-pad"><label>Verified problem<select value={selected} onChange={event => { setSelected(event.target.value); setResult(null); setSent({}); }}><option value="">Select a problem</option>{problems.map(problem => <option key={problem.id} value={problem.id}>{problem.displayId} - {problem.title} - {problem.category}</option>)}</select></label><p className="text-muted" style={{ marginTop: 8 }}>Matching factors: category, subcategory, expertise, location, capacity, resources, previous work, and severity.</p><button className="btn btn-primary" style={{ marginTop: 14 }} onClick={match} disabled={!selected || loading}>{loading ? 'Calculating...' : 'Find exact matches'}</button></div>{result && <div className="matching-results"><div className="card card-pad"><h3>Matched institutes / universities</h3><p className="text-muted">Only the highest-match institute can receive this problem. Other institutes cannot see it in their accounts.</p>{result.institutions?.length ? result.institutions.map((item, index) => orgRow('institution', item, index === 0)) : <p className="text-muted">No institute matched this problem.</p>}</div><div className="card card-pad"><h3>Matched industry partners</h3><p className="text-muted">Industry partners can still be notified when expertise or resources are required.</p>{result.industries?.length ? result.industries.map((item, index) => orgRow('industry', item, index === 0)) : <p className="text-muted">No industry partner matched this problem.</p>}</div></div>}</div>;
}
