import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { getProjectTracking } from '../../api/client';

const directStages = ['Submitted', 'AI Analyzed', 'Government Approval', 'Matched', 'Institute Assigned', 'Team Formation', 'Solution Proposal', 'Prototype/Pilot', 'Closed'];
const collaborationStages = ['Submitted', 'AI Analyzed', 'Government Approval', 'Matched', 'Institute Assigned', 'Team Formation', 'Collaboration Requested', 'Collaboration Accepted', 'Solution Proposal', 'Prototype/Pilot', 'Closed'];
const aliases = { Accepted: 'Institute Assigned', 'Admin Approval': 'Government Approval', 'Industry Collaboration': 'Collaboration Requested', 'In Progress': 'Prototype/Pilot', Implemented: 'Closed', Resolved: 'Closed' };
const statusLabels = { 'Admin Approval': 'Government Approval' };

function Evidence({ records }) { return records?.length ? <div className="card card-pad" style={{ marginTop: 14 }}><h3>Submitted evidence</h3>{records.map(record => <div key={record.id} style={{ borderTop: '1px solid var(--border)', padding: '12px 0' }}><p><b>{record.testType === 'solution' ? 'Solution' : 'Prototype'}</b> · Submitted by: {record.submittedByRole === 'industry_partner' ? 'Industry partner' : record.submittedByRole === 'university_admin' || record.submittedByRole === 'faculty_mentor' ? 'Institute' : record.submittedByRole || 'Project team'}</p>{record.resultSummary && <p>{record.resultSummary}</p>}{record.evidenceUrl && <p><a href={record.evidenceUrl} target="_blank" rel="noreferrer">Open evidence</a></p>}</div>)}</div> : null; }

export default function OrganizationApprovals() {
  const [tracking, setTracking] = useState([]); const [open, setOpen] = useState(null);
  useEffect(() => { getProjectTracking().then(response => setTracking(response.data?.data || [])).catch(error => toast.error(error.response?.data?.error || 'Could not load project tracking.')); }, []);
  return <div><div className="page-head"><h2>Project delivery tracking</h2><p>Track every institute and industry delivery stage, including submitted text, links, images, and documents.</p></div><div className="card">{tracking.length ? tracking.map(project => { const collaboration = project.partnerInterests?.some(item => ['interest_submitted', 'accepted'].includes(item.status)); const stages = collaboration ? collaborationStages : directStages; const currentStage = aliases[project.status] || project.status; const current = stages.indexOf(currentStage); const isOpen = open === project.id; return <div className="card-pad" key={project.id} style={{ borderTop: '1px solid var(--border)' }}><h3>{project.displayId} · {project.title}</h3><p className="text-muted">Institute: {project.university?.name || 'Not assigned'} · Current stage: <b>{statusLabels[project.status] || currentStage}</b></p><p className="text-muted">{collaboration ? 'Collaboration path' : 'Direct institute path'}</p><div className="flow-steps" style={{ marginTop: 18 }}>{stages.map((stage, index) => <div className={`flow-step ${index <= current ? 'active' : ''}`} key={stage}><span className="flow-check">{index <= current ? '✓' : '○'}</span>{stage}</div>)}</div>{project.testingRecords?.length ? <><button className="btn btn-secondary btn-sm" style={{ marginTop: 16 }} onClick={() => setOpen(isOpen ? null : project.id)}>{isOpen ? 'Hide submitted evidence' : `View submitted evidence (${project.testingRecords.length})`}</button>{isOpen && <Evidence records={project.testingRecords} />}</> : <p className="text-muted" style={{ marginTop: 14 }}>No prototype or solution submitted yet.</p>}</div>; }) : <div className="card-pad text-muted">No projects available for tracking yet.</div>}</div></div>;
}
