import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { getProjectTracking } from '../../api/client';

const directStages = ['Submitted', 'AI Analyzed', 'Government Approval', 'Matched', 'Institute Assigned', 'Team Formation', 'Solution Proposal', 'Prototype/Pilot', 'Closed'];
const collaborationStages = ['Submitted', 'AI Analyzed', 'Government Approval', 'Matched', 'Institute Assigned', 'Team Formation', 'Collaboration Requested', 'Collaboration Accepted', 'Solution Proposal', 'Prototype/Pilot', 'Closed'];
const aliases = { Accepted: 'Institute Assigned', 'Admin Approval': 'Government Approval', 'In Progress': 'Prototype/Pilot', Implemented: 'Closed', Resolved: 'Closed' };
const statusLabels = { 'Admin Approval': 'Government Approval' };

export default function OrganizationApprovals() {
  const [tracking, setTracking] = useState([]); const [open, setOpen] = useState(null);
  useEffect(() => { getProjectTracking().then(response => setTracking(response.data?.data || [])).catch(error => toast.error(error.response?.data?.error || 'Could not load project tracking.')); }, []);
  return <div><div className="page-head"><h2>Project delivery tracking</h2><p>Track institute and industry delivery from acceptance to prototype and final submission.</p></div><div className="card">{tracking.length ? tracking.map(project => { const collaboration = project.partnerInterests?.some(item => ['interest_submitted', 'accepted'].includes(item.status)); const stages = collaboration ? collaborationStages : directStages; const currentStage = aliases[project.status] || project.status; const current = stages.indexOf(currentStage); const submission = project.testingRecords?.find(record => record.testType === 'prototype' && (record.submittedByRole || record.resultSummary)); const isOpen = open === project.id; return <div className="card-pad" key={project.id} style={{ borderTop: '1px solid var(--border)' }}><h3>{project.displayId} · {project.title}</h3><p className="text-muted">Institute: {project.university?.name || 'Not assigned'} · Current stage: <b>{statusLabels[project.status] || currentStage}</b></p><p className="text-muted">{collaboration ? 'Collaboration path' : 'Direct institute path'}</p><div className="flow-steps" style={{ marginTop: 18 }}>{stages.map((stage, index) => <div className={`flow-step ${index <= current ? 'active' : ''}`} key={stage}><span className="flow-check">{index <= current ? '✓' : '○'}</span>{stage}</div>)}</div>{submission && <><button className="btn btn-secondary btn-sm" style={{ marginTop: 16 }} onClick={() => setOpen(isOpen ? null : project.id)}>{isOpen ? 'Hide submission details' : 'View submission details'}</button>{isOpen && <div className="card card-pad" style={{ marginTop: 12 }}><h3>Submitted prototype or solution</h3><p className="text-muted">Submitted by: {submission.submittedByRole === 'industry_partner' ? 'Industry partner' : 'Institute'}</p><p>{submission.resultSummary || 'Submission received for review.'}</p>{submission.evidenceUrl && <p><a href={submission.evidenceUrl} target="_blank" rel="noreferrer">Open submitted evidence</a></p>}</div>}</>}</div>; }) : <div className="card-pad text-muted">No projects available for tracking yet.</div>}</div></div>;
}
