import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { decideProjectFinalApproval, getProjectTracking } from '../../api/client';

const directStages = ['Submitted', 'AI Analyzed', 'Government Approval', 'Matched', 'Institute Assigned', 'Team Formation', 'Solution Proposal', 'Prototype/Pilot', 'Government Review', 'Closed'];
const collaborationStages = ['Submitted', 'AI Analyzed', 'Government Approval', 'Matched', 'Institute Assigned', 'Team Formation', 'Collaboration Requested', 'Collaboration Accepted', 'Solution Proposal', 'Prototype/Pilot', 'Government Review', 'Closed'];
const aliases = { Accepted: 'Institute Assigned', 'Admin Approval': 'Government Approval', 'Industry Collaboration': 'Collaboration Requested', 'In Progress': 'Prototype/Pilot', Implemented: 'Closed', Resolved: 'Closed', 'Needs Revision': 'Government Review' };

function Evidence({ records }) { return <div className="card card-pad" style={{ marginTop: 14 }}><h3>Submitted evidence</h3>{records.map(record => <div key={record.id} style={{ borderTop: '1px solid var(--border)', padding: '12px 0' }}><p><b>{record.testType === 'solution' ? 'Solution' : 'Prototype'}</b> · Submitted by: {record.submittedByRole === 'industry_partner' ? 'Industry partner' : record.submittedByRole || 'Project team'}</p>{record.resultSummary && <p>{record.resultSummary}</p>}{record.evidenceUrl && <p><a href={record.evidenceUrl} target="_blank" rel="noreferrer">Open evidence</a></p>}</div>)}</div>; }

export default function OrganizationApprovals() {
  const [tracking, setTracking] = useState([]); const [open, setOpen] = useState(null);
  const load = () => getProjectTracking().then(response => setTracking(response.data?.data || [])).catch(error => toast.error(error.response?.data?.error || 'Could not load project tracking.'));
  useEffect(() => { load(); }, []);
  const review = (project, status) => { const comments = status === 'rejected' ? window.prompt('Enter rejection comments:') : 'Final solution approved.'; if (status === 'rejected' && !comments?.trim()) return; decideProjectFinalApproval(project.id, { status, comments }).then(() => { toast.success(status === 'approved' ? 'Solution approved and resolved.' : 'Solution rejected for revision.'); load(); }).catch(error => toast.error(error.response?.data?.error || 'Could not review the solution.')); };
  return <div><div className="page-head"><h2>Project delivery tracking</h2><p>Track delivery and review final institute or industry submissions.</p></div><div className="card">{tracking.length ? tracking.map(project => { const collaboration = project.partnerInterests?.some(item => ['interest_submitted', 'accepted'].includes(item.status)); const stages = collaboration ? collaborationStages : directStages; const current = stages.indexOf(aliases[project.status] || project.status); const isOpen = open === project.id; const hasFinal = project.testingRecords?.some(record => record.testType === 'solution'); const canReview = hasFinal && ['Submitted', 'Government Review'].includes(project.status); return <div className="card-pad" key={project.id} style={{ borderTop: '1px solid var(--border)' }}><h3>{project.displayId} · {project.title}</h3><p className="text-muted">Institute: {project.university?.name || 'Not assigned'} · Current stage: <b>{aliases[project.status] || project.status}</b></p><div className="flow-steps" style={{ marginTop: 18 }}>{stages.map((stage, index) => <div className={`flow-step ${index <= current ? 'active' : ''}`} key={stage}><span className="flow-check">{index <= current ? '✓' : '○'}</span>{stage}</div>)}</div>{canReview && <div style={{ marginTop: 14 }}><button className="btn btn-primary btn-sm" onClick={() => review(project, 'approved')}>Approve solution</button><button className="btn btn-secondary btn-sm" style={{ marginLeft: 8 }} onClick={() => review(project, 'rejected')}>Reject solution</button></div>}{project.testingRecords?.length ? <><button className="btn btn-secondary btn-sm" style={{ marginTop: 14 }} onClick={() => setOpen(isOpen ? null : project.id)}>{isOpen ? 'Hide submitted evidence' : `View submitted evidence (${project.testingRecords.length})`}</button>{isOpen && <Evidence records={project.testingRecords} />}</> : <p className="text-muted" style={{ marginTop: 14 }}>No prototype or solution submitted yet.</p>}</div>; }) : <div className="card-pad text-muted">No projects available for tracking yet.</div>}</div></div>;
}
