import React, { useEffect, useState } from 'react';
import { getChallenges, updateChallengeStatus } from '../../api/client';
import toast from 'react-hot-toast';

const same = (a, b) => a && b && String(a).trim().toLowerCase() === String(b).trim().toLowerCase();
export default function VerificationQueue() {
  const [items, setItems] = useState([]);
  const load = async () => { try { const response = await getChallenges(); const reports = (response.data?.data || []).filter(report => ['Submitted', 'Under Review'].includes(report.status)); setItems(reports.map(report => ({ ...report, possibleDuplicate: reports.find(other => other.id !== report.id && same(other.category, report.category) && same(other.subcategory, report.subcategory) && same(other.district, report.district)) }))); } catch { toast.error('Could not load reports.'); } };
  useEffect(() => { load(); }, []);
  const act = async (report, status, rejectionReason) => { try { await updateChallengeStatus(report.id, { status, rejectionReason }); toast.success(status === 'Under Review' ? 'Verification staff assignment recorded.' : status === 'Rejected' ? 'Report rejected and citizen notified.' : 'Report verified and ready for matching.'); load(); } catch (error) { toast.error(error.response?.data?.error || 'Could not update the report.'); } };
  return <div><div className="page-head"><h2>Government verification queue</h2><p>Send staff to confirm the location, then accept genuine reports or reject duplicates and invalid reports.</p></div><div className="card">{items.length === 0 ? <div className="card-pad">No pending reports.</div> : items.map(report => <div key={report.id} className="card-pad" style={{ borderBottom: '1px solid var(--border)' }}><h3>{report.displayId} · {report.title}</h3><p className="text-muted">{report.description}</p><p className="text-muted">{report.category} · {report.subcategory || 'General'} · {report.district || 'Location not provided'} · {report.severity || 'Unclassified'}</p><p><b>Verification status:</b> {report.status}</p>{report.possibleDuplicate && <div className="card card-pad" style={{ margin: '10px 0', borderColor: '#f59e0b' }}><b>Possible duplicate:</b> similar report {report.possibleDuplicate.displayId} is registered for the same category and location.</div>}<div>{report.status === 'Submitted' && <button className="btn btn-secondary btn-sm" onClick={() => act(report, 'Under Review')}>Send staff to verify location</button>}{report.status === 'Under Review' && <><button className="btn btn-primary btn-sm" onClick={() => act(report, 'Verified')}>Confirm genuine and match</button>{report.possibleDuplicate && <button className="btn btn-danger btn-sm" onClick={() => act(report, 'Rejected', `Duplicate of ${report.possibleDuplicate.displayId}: this problem is already registered by another user or an earlier report.`)} style={{ marginLeft: 8 }}>Reject as duplicate</button>}<button className="btn btn-secondary btn-sm" onClick={() => act(report, 'Rejected', 'The report could not be verified as a genuine civic problem.')} style={{ marginLeft: 8 }}>Reject report</button></>}</div></div>)}</div></div>;
}
